[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "arch_calculator"
version = "0.1.0"
description = ""
authors = ["Bnbazz <Bnbazz@gmail.com>"]
packages = [
    { include = "core_logic" },
    { include = "desktop_app" }
]
